### ISSUE TITLE
Broken Link (stack-trader GitHub repo)

### ISSUE THREAD

**Issue by andrealmar** [wascc/wascc-dev-site#19]
The link https://github.com/wascc/stack-trader is broken. It is referenced in some places at _wascc.dev_ website

**Comment by autodidaddict** [comment]
Yeah sorry about this, I've "archived" the stack trader repo because it is very, very out of date. Apparently I also hid it so I'll see if I can resurrect that.

**Comment by autodidaddict** [comment]
Made the archived repository visible now, so the links from the wascc.dev site should work.
